version: '3'

services:
  web:
    image: myflaskapp:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
  redis:
    image: "redis:alpine"
